version: "3"
services:
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    ports:
      - 27017:27017
  todo:
    build:
      context: "Todo Server"
    depends_on:
      - "mongodb"
    ports:
      - 8080:3000
    restart: on-failure
    links:
      - mongodb