version: "3"
services:
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    volumes: 
      - "./db:/data/db"
    ports:
      - 27017:27017
  todo:
    build:
      context: "Todo_Server"
    depends_on:
      - "mongodb"
    ports:
      - 8080:3000
    restart: on-failure
    links:
      - mongodb